#!/bin/bash

function echo_run {
    set -x
    "$@"
    set +x
}

OMIT_DIRS=*/site-packages/*

echo "Cleaning up old coverage data"
echo_run rm -rf htmlcov
echo_run rm -rf .coverage

echo "Running bit_manipulation tests..."
coverage run --omit=$OMIT_DIRS ./bit_manip_test.py

echo "Running Memory tests..."
coverage run --omi=$OMIT_DIRS ./memory_test.py

echo "Running RV32ICORE 32-bit tests..."
coverage run --omit=$OMIT_DIRS ./rv32ui_test.py

echo "Running RV64ICORE 64-bit tests..."
coverage run --omit=$OMIT_DIRS ./rv64ui_test.py

echo -e "\nCreating HTML"
coverage html


