#!/bin/bash

function echo_run {
    set -x
    "$@"
    set +x
}

echo "Cleaning up old coverage data"
echo_run rm -rf htmlcov
echo_run rm -rf .coverage

echo "Running bit_manipulation tests..."
coverage run --omit=*/site-packages/* ./bit_manip_test.py

echo "Running RV32ICORE tests..."
coverage run --omit=*/site-packages/* ./rv32ui_test.py

echo -e "\nCreating HTML"
coverage html


